services:
  postgres:
    image: 'postgres:alpine'
    container_name: produtoDB
    environment:
      - 'POSTGRES_DB=produtoDB'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=sa'
    ports:
      - '5432:5432'

  app:
      image: 'openjdk:17-jdk'
      container_name: produtoApp
      depends_on:
        - postgres
      environment:
        - 'SPRING_DATASOURCE_URL=jdbc:postgresql://produtoDB:5432/produtoDB'
        - 'SPRING_DATASOURCE_USERNAME=sa'
        - 'SPRING_DATASOURCE_PASSWORD=password'
      ports:
        - '8082:8082'
      volumes:
        - './target:/app'
      working_dir: /app
      command: [ "java", "-jar", "produto-0.0.1-SNAPSHOT.jar" ]

